audit_header: false
title: Salt Lake City Real Estate Video Blog with Justin Udy
description: >-
  Our mission at Justin Udy & Team Real Estate is to be your best resource for
  Salt Lake City real estate advice. Whether you are a buyer, seller, or
  investor, our team of professionals can answer any questions you might have
  about real estate. If you are looking to buy or sell a home, you can get all
  the information and the latest updates, tips, and tricks from The Justin Udy &
  Team Real Estate, your professional Salt Lake City Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Justin Udy
  title:
  license_number:
  about_markdown: >-
    Justin Udy and Team Real Estate is a group of like-minded, success-hungry
    real estate professionals in Salt Lake City who are one of the highest
    producing teams in the country (In the top 1% according to RealTrends). The
    agents on our team are constantly working to give the best advice, guidance,
    and options to help navigate our clients through buying, selling, and
    investing in real estate.
  brand: Justin Udy & Team Real Estate
  brokerage: Century 21 Everest Realty Group
  market: Salt Lake City
  address: 6925 S. Union Park Center Suite 200<br>Midvale, Utah 84047
  phone: 801-285-0521
  phone_type:
  phone2:
  phone2_type:
  email: Justin@JustinUdy.com
  url: https://JustinUdy.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.justinudy.com/home_value
  second_CTA_text: Home Search
  second_CTA_URL: http://www.saltlakehomesearch.com/
sidebar_CTA:
  - CTA_image_path: >-
      /uploads/6130-murdoch-woods-pl-holladay-print-002-040-exterior-4200x2805-300dpi.jpg
    CTA_title: What’s Your Salt Lake City Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: https://www.justinudy.com/home_value
second_sidebar_CTA:
  - CTA_image_path2: /img/edit_2.jpg
    CTA_title2: Looking for a Salt Lake City Home?
    CTA_text2: Search the entire MLS for your Salt Lake City home.
    CTA_link_text2: Search the MLS
    CTA_url2: http://www.saltlakehomesearch.com/
lender:
  show_section: false
  header_text: Our Preferred Attorney
  headshot_path:
  logo_path: /img/lender-logo.png
  name: EVN Law
  license_number: Real Estate, Business & Start-ups, Securities, Estates, and Litigation
  company: Together We Are <strong>Stronger</strong>
  company_license_number:
  phone:
  email:
  url: http://evnlaw.com
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Justin-Udy-Real-Estate/129849307036755
  linkedin_url: https://www.linkedin.com/in/justinudy
  youtube_url: https://www.youtube.com/channel/UCTTvq11VJt1IX0NIfqyY1xA
  twitter_url: https://twitter.com/justinudy
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Salt Lake City Real Estate Podcast with Justin Udy
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Salt Lake
    City Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Justin Udy & Team Real Estate - your
    professional Salt Lake City Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Salt Lake City,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Justin Udy
images:
  client_headshot_path: /uploads/headshot-beard.png
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Salt Lake City Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#8f92b3'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(250, 250, 250, 0.75)
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: rgba(0, 0, 0, 0)
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: rgba(0, 0, 0, 0)
  secondary_button_text_color: '#ffffff'
